# application properties for  integration test
developer: Jorge Sanchez from application.yaml


spring:
  profiles:
    active:
      integration-test
  datasource:
    url: TBD
    username: TBD
    password: TBD
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
